module.exports = {
  plugins: ["@typescript-eslint"],
  rules: {
    "no-unused-vars": "off",
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/no-unused-vars": [
      "error",
      {
        argsIgnorePattern: "^_",
      },
    ],
    "react/prop-types": "off",
    "import/order": [
      "off",
      {
        alphabetize: {
          order: "asc",
        },
      },
    ],
    "dot-notation": "warn",
    "eqeqeq": "warn",
    "no-else-return": "warn",
    "no-lone-blocks": "warn",
    "no-return-assign": "warn",
    "no-return-await": "warn",
    "no-unused-expressions": "off",
    "@typescript-eslint/no-unused-expressions": [
      "warn",
      { allowShortCircuit: true },
    ],
    "no-useless-concat": "warn",
    "no-lonely-if": "warn",
    "require-await": "warn",
    "wrap-iife": "warn",
    "yoda": "warn",
    "no-unneeded-ternary": "warn",
    "quote-props": ["warn", "consistent-as-needed"],
    "arrow-body-style": "warn",
    "no-useless-computed-key": "warn",
    "no-useless-rename": "warn",
    "no-var": "warn",
    "object-shorthand": "warn",
    "prefer-arrow-callback": "warn",
    "prefer-const": "warn",
    "prefer-destructuring": "warn",
    "prefer-numeric-literals": "warn",
    "prefer-rest-params": "warn",
    "prefer-spread": "warn",
    "prefer-template": "warn",
    "no-empty": ["error", { allowEmptyCatch: true }],
    "curly": ["warn", "multi-line"],
  },
};
